[build]
  command = "npm run build"
  publish = "build"

# Optional: set a Node version for Netlify's build image
[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
